import type { ActivityEvent, Agent, AgentMemory, AgentRun, Approval, AuditLog, DashboardMetric, Integration, IntegrationId, Room, RoomAgent, RoomId, RoomIntegration, RunLog, Task, ToolCall, Workflow, WorkflowStep } from "@/types";
export const workspaceId = "workspace_agent_room" as const;
export const userId = "user_kenan" as const;
const ts = "2026-04-24T15:30:00.000Z";
export const mockRooms: Room[] = [
  { id: "room_fofit", workspaceId, name: "FoFit", slug: "fofit", mission: "Ship a fitness app that turns AI-guided training, progress, and launch operations into one focused founder workflow.", status: "active", accentColor: "#7dd3fc", launchProgress: 64, ownerUserId: userId, createdAt: "2026-04-10T14:00:00.000Z", updatedAt: ts },
  { id: "room_portfolio", workspaceId, name: "Personal Portfolio", slug: "personal-portfolio", mission: "Create a premium founder portfolio that shows products, proof, and current build velocity.", status: "planning", accentColor: "#a7f3d0", launchProgress: 38, ownerUserId: userId, createdAt: "2026-04-12T16:00:00.000Z", updatedAt: ts },
  { id: "room_launch_engine", workspaceId, name: "Launch Engine", slug: "launch-engine", mission: "Reusable operating system for shipping landing pages, content, demos, analytics, and founder launch assets.", status: "active", accentColor: "#f8d77a", launchProgress: 51, ownerUserId: userId, createdAt: "2026-04-14T11:00:00.000Z", updatedAt: ts },
];
const int = (key: Integration["key"], name: string, category: Integration["category"], phase: Integration["phase"], status: Integration["status"], health: Integration["health"], permissionLevel: Integration["permissionLevel"], highRiskActions: Integration["highRiskActions"] = [], errorMessage?: string): Integration => ({ id: `integration_${key}`, key, name, category, phase, status, health, permissionLevel, lastSyncedAt: status === "connected" ? ts : undefined, capabilities: ["activity", "status", "drafts", "sync"], highRiskActions, errorMessage });
export const mockIntegrations: Integration[] = [
  int("github", "GitHub", "code", "phase_1", "connected", "healthy", "execute_with_approval", ["merge_pr"]),
  int("vercel", "Vercel", "deployment", "phase_1", "connected", "degraded", "execute_with_approval", ["deploy_production", "update_env_vars"], "Latest preview deploy needs review before production promotion."),
  int("supabase", "Supabase", "database", "phase_1", "connected", "healthy", "execute_with_approval", ["delete_database_rows", "modify_auth_settings"]),
  int("stripe", "Stripe", "payments", "phase_1", "needs_setup", "unknown", "execute_with_approval", ["create_stripe_product", "change_billing"]),
  int("sentry", "Sentry", "monitoring", "phase_1", "connected", "healthy", "draft_only"),
  int("linear", "Linear", "project_management", "phase_2", "disconnected", "unknown", "draft_only"),
  int("notion", "Notion", "docs", "phase_2", "connected", "healthy", "draft_only"),
  int("figma", "Figma", "design", "phase_2", "connected", "healthy", "read_only"),
  int("canva", "Canva", "marketing", "phase_3", "needs_setup", "unknown", "draft_only", ["send_email"]),
  int("jam", "Jam", "monitoring", "phase_2", "connected", "healthy", "read_only"),
  int("amplitude", "Amplitude", "analytics", "phase_2", "disconnected", "unknown", "read_only"),
  int("cloudflare", "Cloudflare", "infrastructure", "phase_3", "needs_setup", "unknown", "execute_with_approval", ["change_dns"]),
];
const agentSeeds = [
  ["product", "Product Manager Agent", "Product", "planning", "draft_only"],
  ["engineer", "Engineer Agent", "Engineering", "working", "execute_with_approval"],
  ["designer", "Designer Agent", "Design", "reviewing", "draft_only"],
  ["qa", "QA Agent", "Quality", "idle", "read_only"],
  ["growth", "Growth Agent", "Growth", "planning", "draft_only"],
  ["finance", "Finance Agent", "Finance", "blocked", "execute_with_approval"],
  ["security", "Security Agent", "Security", "reviewing", "execute_with_approval"],
  ["deployment", "Deployment Agent", "Deployment", "working", "execute_with_approval"],
] as const;
export const mockAgents: Agent[] = agentSeeds.map(([slug, name, role, status, permissionLevel], i) => ({ id: `agent_${slug}`, workspaceId, name, role, description: `${role} operator for FoFit planning, delivery, launch, and safety.`, status, rolePrompt: `Act as the ${role} lead for the active room.`, integrationIds: mockIntegrations.slice(i % 5, i % 5 + 3).map((x) => x.id), permissionLevel, currentTaskId: `task_${i + 1}`, memorySummary: "FoFit MVP is mock-first, approval-safe, and demo-ready.", suggestedActions: [{ id: `suggest_${slug}`, label: `Review ${role} next move`, description: "Prepare the next safe action for the room.", actionType: "create_draft", riskLevel: "low" }], recentActivityEventIds: [], outputHistory: [{ id: `output_${slug}`, title: `${role} brief`, summary: "Prepared current operating notes.", createdAt: ts }], createdAt: ts }));
const taskTitles = ["Preserve Express live-feed prototype", "Create codex/agent-room-mvp branch", "Scaffold Next.js App Router app", "Configure Tailwind/shadcn dark theme", "Build AppShell, Sidebar, Topbar, CommandBar", "Define TypeScript domain models", "Create mock data", "Build /dashboard", "Build /rooms", "Build FoFit room dashboard", "Build room agents page", "Build task board", "Build activity feed", "Build workflow page", "Build approval center", "Build integration hub", "Build global agent directory", "Build permissions/risk evaluator", "Build mock integration adapters", "Run lint/build/browser QA and update README"];
const statuses: Task["status"][] = ["done", "done", "in_progress", "in_progress", "next", "review", "review", "next", "backlog", "backlog", "backlog", "backlog", "backlog", "backlog", "backlog", "backlog", "backlog", "backlog", "backlog", "backlog"];
export const mockTasks: Task[] = taskTitles.map((title, i) => ({ id: `task_${i + 1}`, roomId: i > 17 ? (i === 18 ? "room_portfolio" : "room_launch_engine") : "room_fofit", title, description: `${title} for the Agent Room mock-first MVP.`, status: statuses[i], priority: i < 5 || [14,17,18].includes(i) ? "urgent" : i < 12 ? "high" : "medium", dueDate: "2026-04-24", assignedAgentId: mockAgents[i % mockAgents.length].id, integrationIds: [mockIntegrations[i % mockIntegrations.length].id], externalLinks: [], createdAt: ts, updatedAt: ts }));
const eventNames = ["GitHub commit pushed", "Vercel preview queued", "Sentry issue grouped", "Stripe trial mocked", "Supabase logs reviewed", "Linear issue moved", "Figma file updated", "Jam bug recorded", "Notion launch brief synced", "Amplitude funnel planned", "Cloudflare DNS approval required", "GitHub PR draft prepared", "Vercel deployment failed", "Supabase schema drafted", "Canva asset queued", "Portfolio spec updated", "Sentry regression watch added", "Stripe product approval created", "Code review queued", "Local Agent Feed preserved"];
export const mockActivityEvents: ActivityEvent[] = eventNames.map((title, i) => ({ id: `event_${i + 1}`, workspaceId, roomId: i === 14 ? "room_launch_engine" : i === 15 ? "room_portfolio" : "room_fofit", actorType: i % 3 === 0 ? "agent" : "integration", actorId: i % 3 === 0 ? mockAgents[i % mockAgents.length].id : mockIntegrations[i % mockIntegrations.length].id, agentId: mockAgents[i % mockAgents.length].id, integrationId: mockIntegrations[i % mockIntegrations.length].id, eventType: title.toLowerCase().replaceAll(" ", "_"), title, summary: `${title} as part of the Agent Room mock operating feed.`, riskLevel: i === 10 ? "critical" : i === 17 ? "high" : i % 4 === 0 ? "medium" : "low", payload: { mock: true }, createdAt: new Date(Date.parse(ts) - i * 420000).toISOString() }));
const risky = ["deploy_production", "merge_pr", "delete_database_rows", "change_dns", "create_stripe_product", "send_email", "update_env_vars", "modify_auth_settings"] as const;
export const mockApprovals: Approval[] = risky.map((actionType, i) => ({ id: `approval_${i + 1}`, workspaceId, roomId: i === 5 ? "room_launch_engine" : "room_fofit", requestedByAgentId: mockAgents[(i + 1) % mockAgents.length].id, actionType, integrationId: mockIntegrations[[1,0,2,11,3,8,1,2][i]].id, summary: `Approve ${actionType.replaceAll("_", " ")} for the mock MVP.`, payload: { actionType }, riskLevel: ["deploy_production", "delete_database_rows", "change_dns", "update_env_vars", "modify_auth_settings"].includes(actionType) ? "critical" : "high", status: "pending", requestedAt: new Date(Date.parse(ts) - i * 500000).toISOString() }));
const workflowNames = ["Fix a bug from Jam", "Ship landing page update", "Deploy FoFit update", "Generate LinkedIn launch post", "Review Sentry error and create GitHub issue", "Turn Figma mockup into implementation plan"];
export const mockWorkflows: Workflow[] = workflowNames.map((name, i) => ({ id: `workflow_${i + 1}`, roomId: i === 1 || i === 3 ? "room_launch_engine" : "room_fofit", name, description: `${name} using mock adapters and approval gates.`, status: i === 3 ? "draft" : "active", triggerType: "manual", stepIds: [1,2,3].map((n) => `workflow_step_${i + 1}_${n}` as const), createdAt: ts }));
export const mockWorkflowSteps: WorkflowStep[] = mockWorkflows.flatMap((workflow, i) => [1,2,3].map((n) => ({ id: `workflow_step_${i + 1}_${n}`, workflowId: workflow.id, position: n, name: ["Collect context", "Draft action", "Request approval"][n - 1], actionType: n === 3 ? (i === 2 ? "deploy_production" : i === 0 ? "merge_pr" : "create_task") : n === 2 ? "create_draft" : "read_activity", integrationId: mockIntegrations[(i + n) % mockIntegrations.length].id, requiresApproval: n === 3 && [0,2,3].includes(i), expectedOutput: "Structured output for the next step." })));
export const mockRoomAgents: RoomAgent[] = mockAgents.map((a) => ({ id: `room_agent_${a.id.replace("agent_", "")}`, roomId: "room_fofit", agentId: a.id, status: a.status, currentTaskId: a.currentTaskId, memorySummary: a.memorySummary }));
export const mockRoomIntegrations: RoomIntegration[] = mockIntegrations.filter((i) => i.phase !== "phase_3").map((i) => ({ id: `room_integration_${i.key}`, roomId: "room_fofit", integrationId: i.id, status: i.status, health: i.health, lastSyncedAt: i.lastSyncedAt }));
export const mockAgentRuns: AgentRun[] = [
  { id: "run_fofit_waitlist_schema", workspaceId, roomId: "room_fofit", agentId: "agent_security", taskId: "task_6", status: "completed", command: "Create FoFit waitlist schema plan", input: { requestedAction: "draft_waitlist_schema", mutationsDisabled: true }, output: "Prepared a waitlist table migration draft and verified that approval is required before applying anything remotely.", startedAt: "2026-04-24T16:50:00.000Z", completedAt: "2026-04-24T16:55:00.000Z", createdAt: "2026-04-24T16:50:00.000Z", updatedAt: "2026-04-24T16:55:00.000Z" },
  { id: "run_fofit_auth_review", workspaceId, roomId: "room_fofit", agentId: "agent_qa", taskId: "task_12", status: "completed", command: "Review FoFit auth flow issue", input: { source: "sentry_mock", mutationsDisabled: true }, output: "Grouped the auth-flow issue into a safe debugging brief with no code mutations.", startedAt: "2026-04-24T16:10:00.000Z", completedAt: "2026-04-24T16:18:00.000Z", createdAt: "2026-04-24T16:10:00.000Z", updatedAt: "2026-04-24T16:18:00.000Z" },
  { id: "run_launch_linkedin_post", workspaceId, roomId: "room_launch_engine", agentId: "agent_growth", taskId: "task_20", status: "running", command: "Generate launch post options", input: { channel: "linkedin", mutationsDisabled: true }, output: "", startedAt: "2026-04-24T17:00:00.000Z", createdAt: "2026-04-24T17:00:00.000Z", updatedAt: "2026-04-24T17:00:00.000Z" },
];
export const mockRunLogs: RunLog[] = [
  { id: "run_log_waitlist_1", workspaceId, runId: "run_fofit_waitlist_schema", level: "info", message: "Created task and selected Database/Security agent lane.", metadata: { localOnly: true }, createdAt: "2026-04-24T16:50:15.000Z" },
  { id: "run_log_waitlist_2", workspaceId, runId: "run_fofit_waitlist_schema", level: "info", message: "Checked Supabase context and prepared migration outline.", metadata: { tool: "supabase", readOnly: true }, createdAt: "2026-04-24T16:51:20.000Z" },
  { id: "run_log_waitlist_3", workspaceId, runId: "run_fofit_waitlist_schema", level: "warn", message: "Remote apply is approval-gated and disabled in mock runtime.", metadata: { approvalRequired: true }, createdAt: "2026-04-24T16:53:00.000Z" },
  { id: "run_log_auth_1", workspaceId, runId: "run_fofit_auth_review", level: "info", message: "Collected Sentry/Jam-style context from the local activity feed.", metadata: { localOnly: true }, createdAt: "2026-04-24T16:10:45.000Z" },
  { id: "run_log_auth_2", workspaceId, runId: "run_fofit_auth_review", level: "info", message: "Produced a debugging brief for the FoFit auth flow.", metadata: { mutationsDisabled: true }, createdAt: "2026-04-24T16:17:30.000Z" },
  { id: "run_log_launch_1", workspaceId, runId: "run_launch_linkedin_post", level: "info", message: "Drafting launch angles from room context.", metadata: { channel: "linkedin" }, createdAt: "2026-04-24T17:00:30.000Z" },
];
export const mockToolCalls: ToolCall[] = [
  { id: "tool_call_waitlist_supabase", workspaceId, runId: "run_fofit_waitlist_schema", integrationId: "integration_supabase", callName: "draft_schema", status: "approval_required", input: { table: "waitlist" }, output: { migrationDrafted: true, applied: false }, startedAt: "2026-04-24T16:51:00.000Z", completedAt: "2026-04-24T16:53:00.000Z", createdAt: "2026-04-24T16:51:00.000Z", updatedAt: "2026-04-24T16:53:00.000Z" },
  { id: "tool_call_auth_sentry", workspaceId, runId: "run_fofit_auth_review", integrationId: "integration_sentry", callName: "read_issue_group", status: "succeeded", input: { mode: "read_only" }, output: { grouped: true, mutation: false }, startedAt: "2026-04-24T16:11:00.000Z", completedAt: "2026-04-24T16:12:30.000Z", createdAt: "2026-04-24T16:11:00.000Z", updatedAt: "2026-04-24T16:12:30.000Z" },
  { id: "tool_call_launch_notion", workspaceId, runId: "run_launch_linkedin_post", integrationId: "integration_notion", callName: "read_launch_brief", status: "running", input: { mode: "read_only" }, output: {}, startedAt: "2026-04-24T17:00:15.000Z", createdAt: "2026-04-24T17:00:15.000Z", updatedAt: "2026-04-24T17:00:15.000Z" },
];
export const mockAgentMemory: AgentMemory[] = [{ id: "memory_fofit_positioning", workspaceId, roomId: "room_fofit", agentId: "agent_product", scope: "room", key: "positioning", value: { statement: "You do not just chat with AI. You manage the work AI is doing." }, source: "founder_brief", createdAt: ts }];
export const mockAuditLogs: AuditLog[] = [{ id: "audit_approval_seed", workspaceId, actorAgentId: "agent_security", action: "approval_policy_seeded", targetType: "approval_policy", targetId: "high_risk_actions", payload: { highRiskActions: 10 }, createdAt: ts }];
export const mockDashboardMetrics: DashboardMetric[] = [{ label: "Active rooms", value: "3", detail: "FoFit is the flagship room", trend: "up" }, { label: "Pending approvals", value: "8", detail: "High-risk actions are gated", trend: "flat" }, { label: "Connected tools", value: "7", detail: "Mock sync across phase 1 and 2", trend: "up" }, { label: "FoFit progress", value: "64%", detail: "MVP foundation", trend: "up" }];
export const getRoomBySlug = (slugOrId: string) =>
  mockRooms.find((r) => r.slug === slugOrId || r.id === slugOrId || (r.id === "room_portfolio" && slugOrId === "portfolio"));
export const getAgent = (id?: string) => mockAgents.find((a) => a.id === id);
export const getIntegration = (id?: IntegrationId) => mockIntegrations.find((i) => i.id === id);
export const getRoomTasks = (roomId: RoomId) => mockTasks.filter((t) => t.roomId === roomId);
export const getRoomEvents = (roomId: RoomId) => mockActivityEvents.filter((e) => e.roomId === roomId);
export const getRoomApprovals = (roomId: RoomId) => mockApprovals.filter((a) => a.roomId === roomId);
export const getRoomWorkflows = (roomId: RoomId) => mockWorkflows.filter((w) => w.roomId === roomId);
export const getWorkflowSteps = (workflowId: string) => mockWorkflowSteps.filter((s) => s.workflowId === workflowId).sort((a, b) => a.position - b.position);
export const getRoomRuns = (roomId: RoomId) => mockAgentRuns.filter((run) => run.roomId === roomId);
export const getRunLogs = (runId: string) => mockRunLogs.filter((log) => log.runId === runId).sort((a, b) => Date.parse(a.createdAt) - Date.parse(b.createdAt));
export const getRunToolCalls = (runId: string) => mockToolCalls.filter((call) => call.runId === runId).sort((a, b) => Date.parse(a.createdAt) - Date.parse(b.createdAt));
export const mockData = { rooms: mockRooms, agents: mockAgents, integrations: mockIntegrations, roomAgents: mockRoomAgents, roomIntegrations: mockRoomIntegrations, tasks: mockTasks, activityEvents: mockActivityEvents, approvals: mockApprovals, workflows: mockWorkflows, workflowSteps: mockWorkflowSteps, agentRuns: mockAgentRuns, runLogs: mockRunLogs, toolCalls: mockToolCalls, agentMemory: mockAgentMemory, auditLogs: mockAuditLogs, metrics: mockDashboardMetrics };
