import Link from "next/link";
import { ArrowRight, PlugZap } from "lucide-react";
import { Avatar, Badge, Button, Card, CardContent, CardHeader, CardTitle, Progress } from "@/components/ui/primitives";
import { formatDateTime, titleCase } from "@/lib/utils";
import { getIntegration, mockTasks } from "@/lib/mock-data";
import type { Agent, AgentStatus, DashboardMetric, Integration, IntegrationHealth, IntegrationStatus, PermissionLevel, RiskLevel, Room, TaskPriority, TaskStatus } from "@/types";
export function AgentStatusBadge({ status }: { status: AgentStatus }) { return <Badge variant={status === "blocked" ? "destructive" : status === "working" ? "success" : "secondary"}>{titleCase(status)}</Badge>; }
export function IntegrationHealthBadge({ health, status }: { health: IntegrationHealth; status?: IntegrationStatus }) { return <Badge variant={status === "needs_setup" || status === "disconnected" ? "outline" : health === "healthy" ? "success" : health === "degraded" ? "warning" : health === "failing" ? "destructive" : "secondary"}>{titleCase(status === "needs_setup" || status === "disconnected" ? status : health)}</Badge>; }
export function PriorityBadge({ priority }: { priority: TaskPriority }) { return <Badge variant={priority === "urgent" ? "destructive" : priority === "high" ? "warning" : "secondary"}>{titleCase(priority)}</Badge>; }
export function TaskStatusBadge({ status }: { status: TaskStatus }) { return <Badge variant="secondary">{titleCase(status)}</Badge>; }
export function RiskBadge({ risk }: { risk: RiskLevel }) { return <Badge variant={risk === "critical" || risk === "high" ? "destructive" : risk === "medium" ? "warning" : "success"}>{titleCase(risk)}</Badge>; }
export function PermissionBadge({ permission }: { permission: PermissionLevel }) { return <Badge variant="outline">{titleCase(permission)}</Badge>; }
export function MetricCard({ metric }: { metric: DashboardMetric }) { return <Card className="glass-panel"><CardHeader className="pb-3"><CardTitle className="text-muted-foreground">{metric.label}</CardTitle></CardHeader><CardContent><div className="text-3xl font-semibold">{metric.value}</div><p className="mt-2 text-sm leading-5 text-muted-foreground">{metric.detail}</p></CardContent></Card>; }
export function RoomCard({ room, featured = false }: { room: Room; featured?: boolean }) { return <Link href={`/rooms/${room.slug}`} className="group block focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><Card className={featured ? "glass-panel border-primary/30" : "glass-panel transition-colors group-hover:border-primary/30"}><CardHeader><div className="flex items-start justify-between gap-4"><div><CardTitle className="text-base">{room.name}</CardTitle><div className="mt-2 flex gap-2"><Badge variant={room.status === "active" ? "success" : "secondary"}>{titleCase(room.status)}</Badge>{featured ? <Badge variant="outline">Flagship</Badge> : null}</div></div><ArrowRight className="size-4 text-muted-foreground transition-transform group-hover:translate-x-1" /></div></CardHeader><CardContent><p className="line-clamp-3 min-h-[72px] text-sm leading-6 text-muted-foreground">{room.mission}</p><div className="mt-5"><div className="mb-2 flex justify-between text-xs text-muted-foreground"><span>Launch progress</span><span>{room.launchProgress}%</span></div><Progress value={room.launchProgress} /></div></CardContent></Card></Link>; }
export function AgentCard({ agent }: { agent: Agent }) { const task = mockTasks.find((t) => t.id === agent.currentTaskId); const tools = agent.integrationIds.map((id) => getIntegration(id)?.name).filter(Boolean); return <Card className="glass-panel"><CardHeader><div className="flex items-start gap-3"><Avatar name={agent.name} /><div className="min-w-0 flex-1"><CardTitle className="truncate text-base">{agent.name}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{agent.role}</p></div><AgentStatusBadge status={agent.status} /></div></CardHeader><CardContent className="flex flex-col gap-4"><p className="text-sm leading-6 text-muted-foreground">{agent.description}</p><div><div className="text-xs font-medium uppercase tracking-[0.16em] text-muted-foreground">Current task</div><p className="mt-1 line-clamp-2 text-sm">{task?.title ?? "No active task"}</p></div><div className="flex flex-wrap gap-2"><PermissionBadge permission={agent.permissionLevel} />{tools.slice(0, 3).map((tool) => <span key={tool} className="rounded-full border px-2.5 py-0.5 text-xs text-muted-foreground">{tool}</span>)}</div></CardContent></Card>; }
export function IntegrationCard({ integration }: { integration: Integration }) { return <Card className="glass-panel"><CardHeader><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-md bg-secondary text-muted-foreground"><PlugZap className="size-4" /></div><div><CardTitle className="text-base">{integration.name}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{titleCase(integration.category)} / {titleCase(integration.phase)}</p></div></div><IntegrationHealthBadge health={integration.health} status={integration.status} /></div></CardHeader><CardContent className="flex flex-col gap-4"><div className="flex flex-wrap gap-2"><PermissionBadge permission={integration.permissionLevel} /><span className="rounded-full border px-2.5 py-0.5 text-xs text-muted-foreground">Last sync: {formatDateTime(integration.lastSyncedAt)}</span></div><p className="text-sm leading-6 text-muted-foreground">{integration.capabilities.join(", ")}</p>{integration.errorMessage ? <p className="rounded-md border border-amber-400/20 bg-amber-400/10 p-3 text-sm text-amber-100">{integration.errorMessage}</p> : null}<Button variant={integration.status === "connected" ? "outline" : "secondary"} size="sm">{integration.status === "connected" ? "Manage" : "Setup"}</Button></CardContent></Card>; }
