import { githubAdapter } from "@/lib/integrations/github";
import { localAgentFeedAdapter } from "@/lib/integrations/local-agent-feed";
import { sentryAdapter } from "@/lib/integrations/sentry";
import { stripeAdapter } from "@/lib/integrations/stripe";
import { supabaseAdapter } from "@/lib/integrations/supabase";
import { vercelAdapter } from "@/lib/integrations/vercel";
import type { IntegrationAdapter } from "@/lib/integrations/types";
import type { IntegrationKey } from "@/types";
export const integrationAdapters: Record<string, IntegrationAdapter> = { github: githubAdapter, vercel: vercelAdapter, supabase: supabaseAdapter, stripe: stripeAdapter, sentry: sentryAdapter, local_agent_feed: localAgentFeedAdapter };
export const getIntegrationAdapter = (key: IntegrationKey) => integrationAdapters[key];
export const listIntegrationAdapters = () => Object.values(integrationAdapters);
export type { IntegrationAdapter } from "@/lib/integrations/types";
