import * as React from "react";
import { cn } from "@/lib/utils";
export function Card({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("min-w-0 overflow-hidden rounded-lg border bg-card text-card-foreground shadow-sm", className)} {...props} />; }
export function CardHeader({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("flex flex-col gap-1.5 p-5", className)} {...props} />; }
export function CardTitle({ className, ...props }: React.HTMLAttributes<HTMLHeadingElement>) { return <h3 className={cn("text-sm font-semibold tracking-normal", className)} {...props} />; }
export function CardContent({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("p-5 pt-0", className)} {...props} />; }
export function Button({ className, variant = "default", size = "md", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "default" | "secondary" | "ghost" | "outline" | "destructive"; size?: "sm" | "md" | "icon" }) { const v = { default: "bg-primary text-primary-foreground hover:bg-primary/90", secondary: "bg-secondary text-secondary-foreground hover:bg-secondary/80", ghost: "hover:bg-secondary text-muted-foreground hover:text-foreground", outline: "border bg-transparent hover:bg-secondary text-foreground", destructive: "bg-red-500 text-white hover:bg-red-500/90" }[variant]; const s = size === "icon" ? "size-10" : size === "sm" ? "h-8 px-3" : "h-10 px-4"; return <button className={cn("inline-flex items-center justify-center gap-2 rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50", v, s, className)} {...props} />; }
export function Badge({ className, variant = "default", ...props }: React.HTMLAttributes<HTMLDivElement> & { variant?: "default" | "secondary" | "outline" | "destructive" | "success" | "warning" }) { const v = { default: "bg-primary text-primary-foreground", secondary: "bg-secondary text-secondary-foreground", outline: "border text-foreground", destructive: "bg-red-400/15 text-red-200", success: "bg-emerald-400/12 text-emerald-200", warning: "bg-amber-400/12 text-amber-200" }[variant]; return <div className={cn("inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium", v, className)} {...props} />; }
export function Progress({ value, className }: { value: number; className?: string }) { return <div className={cn("h-2 overflow-hidden rounded-full bg-secondary", className)}><div className="h-full rounded-full bg-primary transition-all" style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div>; }
export function Avatar({ name, className }: { name: string; className?: string }) { const initials = name.split(" ").map((p) => p[0]).join("").slice(0, 2).toUpperCase(); return <div className={cn("grid size-9 place-items-center rounded-full border bg-secondary text-xs font-semibold", className)} aria-label={name}>{initials}</div>; }
